### ISSUE TITLE
Invalidate an invoice

### ISSUE THREAD

**Issue by NicolasDorier** [ElementsProject/lightning-charge#12]
Use case:

In BTCPay, the user can decide to pay the invoice partly in BTC, partly in LTC, and soon, partly on lightning.

When the invoice is created I create all the addresses in all the alts, and soon, all the invoices on lightning charge. When an address receive a payment, I generate a fresh address. 

But I will also need to generate a new lightning invoice, because the amount due changed.
I would like to invalidate the previous invoice (which has the wrong amount now) if that happen.

This is a "nice to have feature" because I can be sure the user can't screw up and pay too much by mistake. But I can do without, as merchants are kind of used to deal with users sending not enough/too much already.

**Comment by bteitelb** [comment]
The Blockstream Satellite API could also make good use of support for invoice invalidation (i.e. `delinvoice`). If the user orders a message for transmission and then "bumps" it to advance it in the priority queue, the message might be transmitted by the satellites before the invoice corresponding to the bump is paid. In that case, I would like to cancel that invoice.

**Comment by shesek** [comment]
@NicolasDorier @bteitelb Implemented in https://github.com/ElementsProject/lightning-charge/commit/7eddd37ca52fe7e196975ba0d4c70b42648d6e38 as `DELETE /invoice/:id` with `status` in the body.

See: https://github.com/ElementsProject/lightning-charge#delete-invoiceid

**Comment by shesek** [comment]
Does c-lightning provide a way to invalidate an invoice (stop accepting payments to it) without removing the information associated with it? This is probably what I would've preferred doing rather than deleting it entirely. Perhaps charge could keep a copy of the invoice if an `archive` argument is specified?
