### ISSUE TITLE
SyntaxError: Unexpected Idenfier

### ISSUE THREAD

**Issue by A-Diddy** [ElementsProject/lightning-charge#17]
Hi,

Trying the [Getting Started](https://github.com/ElementsProject/lightning-charge#getting-started) section for the first time on a fresh machine and I get the below error when attempting to run `$ charged`. It's probably something I messed up or missed in the config.

```
/usr/local/lib/node_modules/lightning-charge/migrations/20180120115425_completed-fields.js:8
exports.down = async db => {
                     ^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    ...
    at /usr/local/lib/node_modules/lightning-charge/node_modules/knex/lib/migrate/index.js:136:25
    ...
    at Promise._settlePromise (/usr/local/lib/node_modules/lightning-charge/node_modules/bluebird/js/release/promise.js:569:18)
```

Anything obvious? Any suggestions?

My apologies in advance if it's something I missed and thanks for this awesome project!!!!

**Comment by mautematico** [comment]
Duplicated of  #15. Please see solution there. :)

**Comment by shesek** [comment]
Thanks @mautematico! Please let me know if you're still having any issues, @A-Diddy.
