### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by parmax** [ElementsProject/lightning-charge#23]
# npm install -g lightning-charge

npm ERR! code 1
npm ERR! Command failed: /usr/bin/git clone -q git://github.com/shesek/lightning-client-js.git /home/parmax/.npm/_cacache/tmp/git-clone-b5410c31
npm ERR! /home/parmax/.npm/_cacache/tmp/git-clone-b5410c31/.git: Permission denied
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/parmax/.npm/_logs/2018-02-02T17_00_55_324Z-debug.log

**Comment by shesek** [comment]
This looks like a local npm permissions issue. See [the instructions here](https://docs.npmjs.com/getting-started/fixing-npm-permissions) and [this comment](https://github.com/ElementsProject/lightning-charge/issues/8#issuecomment-358281817) for some potential solutions.

**Comment by shesek** [comment]
Closing, please report back if you're still having issues.
