### ISSUE TITLE
charged ALWAYS reports that it is running on localhost, no matter what the host is set to, and will only respond to connections to localhost

### ISSUE THREAD

**Issue by hughfuve** [ElementsProject/lightning-charge#24]
using ubuntu 16.04 LTS, intel core i7-3770

$charged --api-token ??????? # defaults: --ln-path ~/.lightning --db-path ./charge.db --port 9112 --host 192.168.1.5

results in...
HTTP server running on localhost:9112

No GET /invoice/blaaa messages are being generated when I try to connect to http://192.168.1.5:9112/invoice/blaaa , I just get "connection refused".

I tried setting the ip and host on both lightningd (using --ipaddr) and charged, with no change.

I disabled firewall (ufw). no change.

If I connect to 
http://127.0.0.1:9112/invoice/blaaa.
then everything works as expected. 

so as far as I can tell, changing hosts from localhost, does nothing, and trying to connect to the server from any other interface other than localhost is refused.

**Comment by hughfuve** [comment]
oh, I see that "# defaults: " is a comment.. if you want to control those settings then you need...

$charged --api-token ??????? --ln-path ~/.lightning --db-path ./charge.db --port 9112 --host 192.168.1.5

**Comment by hughfuve** [comment]
So I use this to allow connections from any where, with a custom database.

$charged --api-token ???myTokenHere??? --ln-path ~/.lightning --db-path ~/.charge.db --port 9112 --host 0.0.0.0

**Comment by shesek** [comment]
Glad you worked this out, closing the issue. Cheers.
