### ISSUE TITLE
Docker does not work with separate lightningd instance

### ISSUE THREAD

**Issue by NicolasDorier** [ElementsProject/lightning-charge#30]
The charge's docker is messed up if I use a separate lightningd.

`if [ -S /etc/lightning/lightning-rpc ]; then`
problem is: When the dependent lightningd start the socket is not yet created
So charge fire its own lightningd instance...
I think you should keep SKIP_BITCOIND and SKIP_LIGHTNINGD and wait for the file to be created.

**Comment by shesek** [comment]
How about we `if [ -d /etc/lightning ]` instead, then `inotifywait` for the `lightning-rpc` file? That should work too, right?

**Comment by shesek** [comment]
Released in v0.3.8, should be available on docker hub in a few minutes.

**Comment by NicolasDorier** [comment]
Trying with 0.3.9 it works.
