### ISSUE TITLE
node-pre-gyp ERR! UNCAUGHT EXCEPTION

### ISSUE THREAD

**Issue by 52edc** [ElementsProject/lightning-charge#37]
Hello 

c-lightning is working almost fine, I opened a few channels and made some payments. 

I tried to install "lightning charge" but no success :( Can you help?

`root@vmi178998:~# sudo npm install -g lightning-charge
/usr/local/bin/charged -> /usr/local/lib/node_modules/lightning-charge/bin/charged

> sqlite3@4.0.0 install /usr/local/lib/node_modules/lightning-charge/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! UNCAUGHT EXCEPTION
node-pre-gyp ERR! stack TypeError: Buffer.alloc is not a function
node-pre-gyp ERR! stack     at Object.<anonymous> (/usr/local/lib/node_modules/lightning-charge/node_modules/sqlite3/node_modules/tar/lib/pack.js:32:20)
node-pre-gyp ERR! stack     at Module._compile (module.js:410:26)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:417:10)
node-pre-gyp ERR! stack     at Module.load (module.js:344:32)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:301:12)
node-pre-gyp ERR! stack     at Module.require (module.js:354:17)
node-pre-gyp ERR! stack     at require (internal/module.js:12:17)
node-pre-gyp ERR! stack     at Object.<anonymous> (/usr/local/lib/node_modules/lightning-charge/node_modules/sqlite3/node_modules/tar/lib/create.js:6:14)
node-pre-gyp ERR! stack     at Module._compile (module.js:410:26)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:417:10)
node-pre-gyp ERR! System Linux 4.4.0-121-generic
node-pre-gyp ERR! command "/usr/bin/nodejs" "/usr/local/lib/node_modules/lightning-charge/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/lightning-charge/node_modules/sqlite3
node-pre-gyp ERR! node -v v4.2.6
node-pre-gyp ERR! node-pre-gyp -v v0.9.0
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>
/usr/local/lib
└── (empty)

npm ERR! Linux 4.4.0-121-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "lightning-charge"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@4.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the sqlite3@4.0.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sqlite3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
npm ERR! code 1
`

npm-debug.log file here: https://pastebin.com/y7FvRBc0

Thank you
P.

**Comment by shesek** [comment]
What version of nodejs are you running? As mentioned on the README, Lightning Charge requires `v7.6` or newer, the lack of `Buffer.alloc()` appears to indicate `<v5.10.0`.

**Comment by shesek** [comment]
Closing, please report back if you're still having issues.
