### ISSUE TITLE
Problem with sqlite3

### ISSUE THREAD

**Issue by johneakin** [ElementsProject/lightning-charge#43]
charged --api-token password
Knex: run
$ npm install sqlite3 --save
Error: Cannot find module '/home/pi/.npm-global/lib/node_modules/lightning-charge/node_modules/sqlite3/lib/binding/node-v51-linux-arm/node_sqlite3.node'

and the followings always errors
npm install sqlite3 --save

Any idea?

**Comment by shesek** [comment]
Discussed over email, this was the same issue as https://github.com/ElementsProject/lightning-charge/issues/16 (switching node versions between installing and running).
