### ISSUE TITLE
ARMv7 

### ISSUE THREAD

**Issue by normandmickey** [ElementsProject/lightning-charge#47]
Do you have any plans to release this to run on ARM processors?  If not do you have any suggestions on how to change it to run on ARM?

**Comment by shesek** [comment]
Running Lightning Charge on ARM is possible, check out @grubles's tutorial at https://hackernoon.com/how-to-build-your-own-portable-plug-in-lightning-node-c4093a4b10fb

**Comment by normandmickey** [comment]
Thanks, I have managed to get Lightning charge to work on an ARM but was
hoping to find a docker-compose that put it all together.

**Comment by shesek** [comment]
Lightning Charge doesn't have an example docker-compose setup, but does have a docker image that you can use. By default, this image already comes bundled with `bitcoind`+`lightningd`+`charged`, which might be sufficient for your needs.

If you do end up writing a docker-compose setup, let me know and I'll look into adding that to the instructions here.
