### ISSUE TITLE
Failed to install with node10 on FreeBSD 12

### ISSUE THREAD

**Issue by reablaz** [ElementsProject/lightning-charge#59]
Failed to install package with npm@node10 on FreeBSD10. If npm@node8 is used package install is succesfull.

Errorlog:

`npm install --unsafe-perm -g lightning-charge --sqlite=/usr/local`

> 16159 info lifecycle sqlite3@4.0.4~install: sqlite3@4.0.4
> 16160 verbose lifecycle sqlite3@4.0.4~install: unsafe-perm in lifecycle true
> 16161 verbose lifecycle sqlite3@4.0.4~install: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/local/lib/node_modules/lightning-charge/node_modules/sqlite3/node_modules/.bin:/usr/local/lib/node_modules/lightning-charge/node_modules/.bin:/usr/local/lib/node_modules/.bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/games:/usr/local/sbin:/usr/local/bin:/root/bin
> 16162 verbose lifecycle sqlite3@4.0.4~install: CWD: /usr/local/lib/node_modules/lightning-charge/node_modules/sqlite3
> 16163 silly lifecycle sqlite3@4.0.4~install: Args: [ '-c', 'node-pre-gyp install --fallback-to-build' ]
> 16164 silly lifecycle sqlite3@4.0.4~install: Returned: code: 1  signal: null
> 16165 info lifecycle sqlite3@4.0.4~install: Failed to exec install script
> 16166 timing action:install Completed in 14059ms
> 16167 verbose unlock done using /root/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
> 16168 timing stage:rollbackFailedOptional Completed in 2041ms
> 16169 timing stage:runTopLevelLifecycles Completed in 34196ms
> 16170 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/lightning-charge/node_modules/fsevents):
> 16171 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"freebsd","arch":"x64"})
> 16172 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
> 16172 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
> 16172 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   freebsd
> 16172 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
> 16173 verbose stack Error: sqlite3@4.0.4 install: `node-pre-gyp install --fallback-to-build`
> 16173 verbose stack Exit status 1
> 16173 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
> 16173 verbose stack     at EventEmitter.emit (events.js:189:13)
> 16173 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
> 16173 verbose stack     at ChildProcess.emit (events.js:189:13)
> 16173 verbose stack     at maybeClose (internal/child_process.js:970:16)
> 16173 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
> 16174 verbose pkgid sqlite3@4.0.4
> 16175 verbose cwd /root
> 16176 verbose FreeBSD 12.0-RELEASE
> 16177 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--unsafe-perm" "-g" "lightning-charge" "--sqlite=/usr/local"
> 16178 verbose node v10.15.3
> 16179 verbose npm  v6.9.0
> 16180 error code ELIFECYCLE
> 16181 error errno 1
> 16182 error sqlite3@4.0.4 install: `node-pre-gyp install --fallback-to-build`
> 16182 error Exit status 1
> 16183 error Failed at the sqlite3@4.0.4 install script.
> 16183 error This is probably not a problem with npm. There is likely additional logging output above.
> 16184 verbose exit [ 1, true ]

**Comment by dakk** [comment]
@reablaz got the same problem (on FreeBSD) with this and other packages which depends on sqlite3, but I think it's a problem related to sqlite3 package. 

https://github.com/mapbox/node-sqlite3

**Comment by reablaz** [comment]
There is a package sqlite3@4.0.6 which installs on without problem. maybe there is a way to use newer sqlite3 version in dependencies

**Comment by shesek** [comment]
Thanks for the report!

Updated sqlite3 to v4.0.6 (plus a bunch of other dependencies) in 0d40dfd, released in v0.4.8.

Please let me know if this fixes the issue.

**Comment by shesek** [comment]
> `--unsafe-perm`

You shouldn't have to do this, [following these instructions](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally#manually-change-npms-default-directory) should get charge to install properly by your user account without unsafe-perm.

**Comment by reablaz** [comment]
> > `--unsafe-perm`
> 
> You shouldn't have to do this, [following these instructions](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally#manually-change-npms-default-directory) should get charge to install properly by your user account without unsafe-perm.

Thank you for pointing! Yes, package should be normally installed without this parameter. I think that was the one of the commands i tried in hope it helps.
