### ISSUE TITLE
Enable https on lightning-charge

### ISSUE THREAD

**Issue by alexaumaitre** [ElementsProject/lightning-charge#60]
Hi everyone,
Is there a way to enable HTTPS on lightning-charge ?
I've tried to enable this via a proxy HTTPS based on Apache but it doesn't seem to work because of the API key added in urls.
Thanks in advance for your advices.

**Comment by shesek** [comment]
The `http(s)://username:password@foobar.com/` URI format is a standard way to authenticate using [http basic access authentication](https://en.wikipedia.org/wiki/Basic_access_authentication) and should work well with reverse proxies like Apache. How did you try setting this up and what isn't working exactly?

**Comment by alexaumaitre** [comment]
I need to set a reverse proxy server to enable HTTPS (which is essential for security).

Apparently, it's not possible to pass login and pass in url when you enable a reverse proxy server in Apache.

Then it's not possible to redirect to this url http://api-token:MYAPIKEY@127.0.0.1:9112/

In the apache2.conf, you need to encode the api-token:MYAPIKEY in base 64 and to pass it in the request header.

For example, I try to setup a redirect from https://myserver:443/lnrpc to http://127.0.0.1:9112/

```
<VirtualHost *:443>
        SSLEngine On

        SSLCertificateFile /home/bitcoin/.lightning/server.cert
        SSLCertificateKeyFile /home/bitcoin/.lightning/server.pem

        RequestHeader set Authorization "Basic <base64 api-token:MYAPIKEY>"

        ProxyPass /lnrpc http://127.0.0.1:9112/
        ProxyPassReverse /lnrpc http://127.0.0.1:9112/
</VirtualHost>
```

Unfortunatly, when I try to call the url https://myserver:443/lnrpc/info I get the message : "Cannot GET //info".

Do you have any idea  to help me ?

**Comment by alexaumaitre** [comment]
Ok finalement c'était vraiment un point purement lié à Apache.
Apache n'aime pas du tout les redirection depuis une subdirectory et il vaut mieux passer la clé api directement dans l'url.

Exemple :
on redirige https://api-token:MYAPIKEY@myserver:443/ --> https://api-token:MYAPIKEY@localhost:9112/

Merci pour votre aide.
