### ISSUE TITLE
Support for connecting to remote Lightningd instances.

### ISSUE THREAD

**Issue by gijswijs** [ElementsProject/lightning-charge#62]
Let me start out by saying that I don't understand unix sockets, so please bear with me while I ask dumb questions.

If I check the [readme.md of lightning itself](https://github.com/ElementsProject/lightning) it states:

> Here is an example of a docker-compose file with bitcoind and c-lightning on testnet which expose [...] c-lightning API on port 9735

Now what's the use of exposing an API on a port if you don't want people to remotely connect with it?

How do you connect with it? All the clients that I have seen all need you to point to the lightning-rpc itself (e.g. `~/.lightning/lightning-rpc`) so they seem to be only usable on the same machine as where c-lightning is running. So how would you go about with accessing that exposed RPC remotely?

The readme.md of lightning-charge states: 

> Connecting to remote lightningd instances is currently not supported.

If it's possible to connect via that exposed RPC port, is it on lightning-charge's roadmap to support that?

Any help would be appreciated.

**Comment by shesek** [comment]
> Now what's the use of exposing an API on a port if you don't want people to remotely connect with it?

The `EXPOSE_TCP` option of the docker image is only meant for development/testing, not for real use. It provides no authentication or encryption, anyone who could connect to this port would gain full control over your wallet. Note that the readme mentions "(Use this only for testing)".

> If it's possible to connect via that exposed RPC port, is it on lightning-charge's roadmap to support that?

It is not. Using the rpc directly over tcp is unsafe and therefore unsupported.

However, you can use an ssh tunnel to forward a local unix socket to a remote one. For example, this command:

```bash
$ ssh -nNT -L $HOME/lightning-rpc.sock:/home/satoshi/.lightning/lightning-rpc satoshi@someremote
```

Would create a local unix socket at `~/lightning-rpc.sock` which forwards to the `/home/satoshi/.lightning/lightning-rpc` unix socket on the remote machine. You could then point c-lightning clients to use this unix socket, just like you would use a regular local unix socket.

**Comment by gijswijs** [comment]
> Using the rpc directly over tcp is unsafe and therefore unsupported

Understood. But I *am* in a testing environment, only using regtest.

So then it would be possible to connect remotely over TCP, right?

(Nonetheless, I completely understand why this isn't on the roadmap)

Thanks fro replying.

**Comment by gijswijs** [comment]
It *is* possible, but bear in mind that `EXPOSE_TCP` is implemented in c-lightning's docker script:

https://github.com/ElementsProject/lightning/blob/2945b25b57db37dca31c10da34a4b1ca33d697c3/Dockerfile#L103

https://github.com/ElementsProject/lightning/blob/master/tools/docker-entrypoint.sh

If you didn't use that script or didn't implement it in your own docker script, it won't work.

It's easy to mistake EXPOSE_TCP for a parameter you can set when spinning up c-lighting.
