### ISSUE TITLE
Support CORS

### ISSUE THREAD

**Issue by TerjeNorderhaug** [ElementsProject/lightning-charge#64]
I am experimenting with accessing Lightning Charge directly from a web browser locally without server proxying, but quickly run into CORS issues. 

It would be great if Lightning Charge enabled CORS, e.g. by using the [cors middleware](https://www.npmjs.com/package/cors) in [app.js:](https://github.com/ElementsProject/lightning-charge/blob/master/src/app.js)

```javascript
app.use(require('cors')())
```

**Comment by shesek** [comment]
Are you sure you want to access Lightning Charge directly from the web browsers? This would give clients the ability to list all the invoices ever created by the lightning charge instance, their status, their description, associated metadata, etc.

Typically, you would have some server-side code that talks with lightning charge and exposes a more restricted API to the outside world.

**Comment by TerjeNorderhaug** [comment]
I'd like to access Lightning Charge from code in a web browser on the same host as lightning charge (or with privileged access). This doesn't imply providing unrestricted access from the outside world.

**Comment by shesek** [comment]
Implemented in https://github.com/ElementsProject/lightning-charge/commit/37af9737b3f849df9b432e6887beed7612dc8e35
