### ISSUE TITLE
please remove .git from npm package

### ISSUE THREAD

**Issue by kaminskypavel** [ElementsProject/lightning-charge#66]
@shesek , it looks like the package on npm containing a .git folder.
this is breaks any npm installs in the recent versions of npm as you can see

```
$ npm i -D @types/axios
npm WARN deprecated @types/axios@0.14.0: This is a stub types definition for axios (https://github.com/mzabriskie/axios). axios provides its own type definitions, so you don't need @types/axios installed!
npm ERR! path D:\devl\buidl-tlv-2019\spark-gatway-server\node_modules\lightning-charge
npm ERR! code EISGIT
npm ERR! git D:\devl\buidl-tlv-2019\spark-gatway-server\node_modules\lightning-charge: Appears to be a git repo or submodule. npm ERR! git     D:\devl\buidl-tlv-2019\spark-gatway-server\node_modules\lightning-charge
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.```


a temporary WO is to delete it manually from node_modules

**Comment by kaminskypavel** [comment]
this apparently happens with  the following module as well

``` 
npm ERR! git D:\devl\buidl-tlv-2019\spark-gatway-server\node_modules\lightning-charge\node_modules\lightning-client\node_modules\error: Appears to be a git repo or submodule.
```

you can read more on the issue [here](https://github.com/react-native-community/react-native-safe-area-view/issues/73)

**Comment by shesek** [comment]
Thanks for the report!

I checked and the package does not seem to currently have `.git` in it.

The error related to the `error` package was due to `lightning-client` loading it from git and not from the npm registry, but this is no longer the case as of https://github.com/shesek/lightning-client-js/commit/df49c91b0a1b926b8dfa69620956d6ecbc7a2b9b.
