### ISSUE TITLE
Support for v0.8.0?

### ISSUE THREAD

**Issue by LightningK0ala** [ElementsProject/lightning-charge#69]
After upgrading c-lightning to v0.8.0 I'm getting an error with lightning-charge:

```
 Lightning client connection error { Error: connect ECONNREFUSED /root/.lightning/lightning-rpc
     at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
   errno: 'ECONNREFUSED',
   code: 'ECONNREFUSED',
   syscall: 'connect',
   address: '/root/.lightning/lightning-rpc' }
 events.js:183
       throw er; // Unhandled 'error' event
       ^

 Error: connect ECONNREFUSED /root/.lightning/lightning-rpc
     at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
```

I'm on lightning charge v0.4.13

**Comment by shesek** [comment]
I haven't had the chance to test with v0.8.0 yet, but this might be due to c-lightning using subdirectories for networks now. Try starting spark with `--ln-path /root/.lightning/<network>`.

**Comment by shesek** [comment]
I could make the migration easier for users, created https://github.com/ElementsProject/lightning-charge/issues/70 and https://github.com/shesek/spark-wallet/issues/130 to keep track of that.

**Comment by LightningK0ala** [comment]
Starting spark with `--ln-path /root/.lightning/bitcoin` worked! You were right about the subdirectory, thanks @shesek!
