### ISSUE TITLE
npm installation fails

### ISSUE THREAD

**Issue by melvincarvalho** [ElementsProject/lightning-charge#8]
**Command** : `sudo npm install -g lightning-charge`

**Hardware**:  raspberry pi 3

**OS**: Raspbian

**Error**

```
$ sudo npm install -g lightning-charge
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone -q git://github.com/shesek/lightning-client-js.git /root/.npm/_cacache/tmp/git-clone-42cb7618
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-42cb7618': Permission denied
npm ERR! 
```

Im possibly doing something stupid here.  Any insights?

**Comment by melvincarvalho** [comment]
Same issue on ubuntu 16.04

**Comment by shesek** [comment]
This looks like a local npm/permissions issue. You can try following the instructions [here](https://docs.npmjs.com/getting-started/fixing-npm-permissions#option-two-change-npms-default-directory) to make npm install global packages to your user's home directory without requiring the use of `sudo`. Let me know if that helps!

**Comment by Head** [comment]
same here and no idea why `npm` sucks so bad... Tried `yarn global add lightning-charge` and it works fine. Just install `yarn` with `npm install -g yarn` first.

**Comment by melvincarvalho** [comment]
@shesek Thank you, that worked!

[npx](https://github.com/zkat/npx) suggested on the same page also worked.

Closing.
